# Generated by Django 4.2.7 on 2023-11-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
