# Generated by Django 4.2.7 on 2023-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0002_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
